version: 2.1
jobs:
  tflint:
    machine: true
    steps:
      - checkout
      - run:
          name: Run TFLint
          command: docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint --chdir=aws -f json | tee tflint-output.json || true
      - store_artifacts:
          path: tflint-output.json
          destination: tflint-artifact
  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"
  integration:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
  prod:
    machine: true
    steps:
      - checkout
      - run: echo "This is a deploy step"
workflows:
  version: 2
  django:
    jobs:
      - tflint
      - test:
          requires:
            - tflint
      - integration:
          requires:
            - test
      - hold-prod-approval:
          type: approval
          requires:
            - integration
      - prod:
          requires:
            - hold-prod-approval
